# 2.Python科学计算
本次我们对Python常用的科学计算模块进行基本介绍，在Python中常用的这类模块主要有四个：
- numpy 储存数据，高效的（多维）数组操作
- scipy 数学计算模块，例如信号处理、最优化，本课我们不直接使用，以上两项近似matlab
- pandas 数据容器，储存检视，基本序列操作。近似于excel
- Matplotlib 绘图工具，进行较为严肃的数据可视化

## 2.1 numpy
- 无套利的原则在计算机的世界中依然存在，
- 高效运行、灵活通用、简单易学 是编程语言中的“不可能三角”
- Python的list十分灵活，但这种灵活的代价是运行效率相对缓慢

于是numpy被发明，在牺牲了部分“灵活通用”的前提下，极大地提高了科学计算相关的计算效率

### 2.1.1 创造一个数组

In [1]:
import numpy as np
import pandas as pd

In [2]:
# 包名.<TAB>获取列表
# 后面加问号获取帮助文档（备忘而非学习）
np?
np.add?

In [3]:
ar1 = np.array([0,1,2,3])
ar2 = np.array([0.0,1.0,2.0,3.0])
ar3 = np.array([0,1,2,3.0])
ar4 = np.array([0,1,'2',3.0])

In [4]:
ar1

array([0, 1, 2, 3])

In [5]:
ar2

array([0., 1., 2., 3.])

In [6]:
ar3

array([0., 1., 2., 3.])

In [7]:
ar4

array(['0', '1', '2', '3.0'], dtype='<U21')

In [8]:
print(ar1.dtype)
print(ar2.dtype)
print(ar3.dtype)
print(ar4.dtype)

int64
float64
float64
<U21


In [22]:
ar4.dtype?

In [9]:
ar5 = np.array([1,2,3,4],dtype='float32')
ar6 = np.array([1.0,2.1,3.5,4.9],dtype='int32')

In [10]:
ar5

array([1., 2., 3., 4.], dtype=float32)

In [11]:
ar6

array([1, 2, 3, 4], dtype=int32)

In [12]:
print(ar5.dtype)
print(ar6.dtype)

float32
int32


In [13]:
mat1 = np.array([[0,1,2],[3,4,5],[6,7,8]])
mat2 = np.array([[0,1.0,2],[3,4,5],[6,7,8]])
mat3 = np.array([[0,1.0,2],[3,4,5],[6,7,8,9]])

In [14]:
mat1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [15]:
mat2

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [16]:
mat3

array([list([0, 1.0, 2]), list([3, 4, 5]), list([6, 7, 8, 9])],
      dtype=object)

In [18]:
ts1 = np.array([[[0,1],[2,3]],[[4,5],[6,7]]])
ts2 = np.array([[[0,1],[2,3]],[[4,5],[6]]])

In [19]:
ts1

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [38]:
ts2

array([[list([0, 1]), list([2, 3])],
       [list([4, 5]), list([6])]], dtype=object)

- 初始化类型

In [20]:
ar0 = np.zeros(10,dtype = int)
ar1 = np.empty(10)
ar2 = np.ones((2,3),dtype = float)
ar3 = np.full((2,2,3),2.33)
ar4 = np.identity(5)

In [21]:
ar0,ar1,ar2,ar3,ar4

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0]),
 array([-2.00000000e+000,  2.32035977e+077,  3.45845952e-323,
         0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
         0.00000000e+000,  0.00000000e+000,  0.00000000e+000,
         0.00000000e+000]),
 array([[1., 1., 1.],
        [1., 1., 1.]]),
 array([[[2.33, 2.33, 2.33],
         [2.33, 2.33, 2.33]],
 
        [[2.33, 2.33, 2.33],
         [2.33, 2.33, 2.33]]]),
 array([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]]))

- 更加复杂的单矩阵

In [22]:
i1 = np.eye(5)
i2 = np.eye(5,7)
i3 = np.eye(5,7,k=2)
i4 = np.eye(5,7,k=-2)
i5 = np.eye(5,7,k=-10)

In [23]:
i1

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [24]:
i2

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.]])

In [76]:
i3

array([[0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [77]:
i4

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.]])

In [78]:
i5

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

- 区间生成数

In [25]:
ar5 = np.arange(0,20,3)
ar6 = np.linspace(10,30,7)


In [26]:
ar5,ar6

(array([ 0,  3,  6,  9, 12, 15, 18]),
 array([10.        , 13.33333333, 16.66666667, 20.        , 23.33333333,
        26.66666667, 30.        ]))

- 随机化

In [28]:

ar7 = np.random.random((4,3))
ar8 = np.random.normal(0,1,(4,4))
ar9 = np.random.randint(0,9,(3,3))

In [29]:
ar7,ar8,ar9

(array([[0.11827443, 0.63992102, 0.14335329],
        [0.94466892, 0.52184832, 0.41466194],
        [0.26455561, 0.77423369, 0.45615033],
        [0.56843395, 0.0187898 , 0.6176355 ]]),
 array([[ 1.53277921,  1.46935877,  0.15494743,  0.37816252],
        [-0.88778575, -1.98079647, -0.34791215,  0.15634897],
        [ 1.23029068,  1.20237985, -0.38732682, -0.30230275],
        [-1.04855297, -1.42001794, -1.70627019,  1.9507754 ]]),
 array([[4, 6, 4],
        [4, 3, 4],
        [4, 8, 4]]))

In [30]:
np.random.seed(0)
ra1 = np.random.random((3,4))
ra1c = np.random.random((3,4))

In [31]:
ra1,ra1c

(array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
        [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
        [0.96366276, 0.38344152, 0.79172504, 0.52889492]]),
 array([[0.56804456, 0.92559664, 0.07103606, 0.0871293 ],
        [0.0202184 , 0.83261985, 0.77815675, 0.87001215],
        [0.97861834, 0.79915856, 0.46147936, 0.78052918]]))

In [32]:
np.random.seed(0)
ra2 = np.random.random((3,4))
ra2c = np.random.random((3,4))

In [33]:
ra2,ra2c

(array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
        [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
        [0.96366276, 0.38344152, 0.79172504, 0.52889492]]),
 array([[0.56804456, 0.92559664, 0.07103606, 0.0871293 ],
        [0.0202184 , 0.83261985, 0.77815675, 0.87001215],
        [0.97861834, 0.79915856, 0.46147936, 0.78052918]]))

### 2.1.2 数组属性

- 维度

In [34]:

ar1 = np.ones((3,4,5))
print(ar1.ndim,'\n',ar1.shape,'\n',ar1.size)
print(len(ar1))
print(len(ar1[0]))
print(len(ar1[0][0]))

3 
 (3, 4, 5) 
 60
3
4
5


- 数据类型

In [36]:
ar1 = np.array([0,1])
ar2 = np.array([0.0,1])
ar3 = np.array([2,3])

print(ar1.dtype)
print(ar2.dtype)
print(ar1.dtype == ar3.dtype)
print(ar1.dtype == ar2.dtype)
print(ar1.dtype > ar2.dtype)
print(ar1.dtype < ar2.dtype)

int64
float64
True
False
False
True


In [37]:


ar4 = np.array([2,'333'])
print(ar2.dtype < ar4.dtype)
print(ar2.dtype > ar4.dtype)
print(ar2.dtype == ar4.dtype)

print(ar1.itemsize)
print(ar1.nbytes)
print(ar2.itemsize)
print(ar2.nbytes)
print(ar4.itemsize)
print(ar4.nbytes)

False
False
False
8
16
8
16
84
168


In [38]:
ar4 = np.array([[0,1],[2,3]])
ar4.dtype = float
ar4

array([[0.0e+000, 4.9e-324],
       [9.9e-324, 1.5e-323]])

In [132]:
ar4 = np.array([[0,1],[2,3]])
ar4 = ar4.astype(np.float)
ar4

array([[0., 1.],
       [2., 3.]])

### 2.1.3 数组索引

- 索引

In [40]:
ar = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
ar

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [41]:
ar[0,2]

3

In [42]:
ar[0,:]

array([1, 2, 3, 4])

In [43]:
ar[0]

array([1, 2, 3, 4])

In [45]:
ar[0,2] = 5.14
ar

array([[ 1,  2,  5,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [46]:
ar[0,2] = '3'
ar

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [47]:
ar[0,2] = '3.14'
ar

ValueError: invalid literal for int() with base 10: '3.14'

- 切片

In [48]:
ar1 = np.array(range(20))
ar1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [146]:
ar1[3::3]

array([ 3,  6,  9, 12, 15, 18])

In [144]:
ar1[5::-1]

array([5, 4, 3, 2, 1, 0])

In [145]:
ar1[:10:-2]

array([19, 17, 15, 13, 11])

In [49]:
ar

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [52]:
ar[[0,1,2],[1,2,3]]

array([ 2,  7, 12])

In [50]:
ar[:2,1:2]

array([[2],
       [6]])

In [55]:
ar[::-1,::2]

array([[ 9, 11],
       [ 5,  7],
       [ 1,  3]])

In [56]:
ar[::-1,::-2]

array([[12, 10],
       [ 8,  6],
       [ 4,  2]])

In [155]:
ar[:,2]

array([ 3,  7, 11])

In [157]:
ar[:,2][::-1]

array([11,  7,  3])

In [156]:
ar[1,:]

array([5, 6, 7, 8])

In [57]:
ar

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [58]:
sub_ar = ar[1:,:2]
sub_ar

array([[ 5,  6],
       [ 9, 10]])

In [59]:
sub_ar[1,1] = -2.5

In [60]:
sub_ar

array([[ 5,  6],
       [ 9, -2]])

In [61]:
ar

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, -2, 11, 12]])

In [62]:
int(-3.9)

-3

In [63]:
ar_s = np.ones((2,2))
sub_ar = ar_s
ar

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, -2, 11, 12]])

数据很大时，用切片灵活高效地修改部分

In [66]:
sub_ar_c = ar[1:,:2].copy()
sub_ar_c = sub_ar_c-10
ar

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, -2, 11, 12]])

In [67]:
sub_ar_c

array([[ -5,  -4],
       [ -1, -12]])

In [68]:
ar[[0,2],[2,1]]

array([ 3, -2])

- 布尔索引

In [69]:
ar

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, -2, 11, 12]])

In [71]:
ar %2 == 0

array([[False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True]])

In [72]:
ar[ar > 0]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12])

In [73]:
ar[ar < 4]

array([ 1,  2,  3, -2])

In [74]:
len(ar[ar < 4])

4

In [75]:
ar[ar<4] = 4
ar

array([[ 4,  4,  4,  4],
       [ 5,  6,  7,  8],
       [ 9,  4, 11, 12]])

In [76]:
ar[(ar>4)&(ar<8)]

array([5, 6, 7])

In [78]:
ar[ar>4&ar<8]

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [196]:
ar

array([[ 4,  4,  4,  4],
       [ 5,  6,  7,  8],
       [ 9,  4, 11, 12]])

In [81]:
17&16

16

In [82]:
ar[1&ar==1] #按位与 和 与 歧义

array([ 5,  7,  9, 11])

### 2.1.4 数组变形、拼接、分裂

- 变形

In [83]:
ar1 = np.array(range(1,13))
print(ar1)
ar = ar1.reshape((3,4))
ar

[ 1  2  3  4  5  6  7  8  9 10 11 12]


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [84]:
ar2 = ar1.reshape((1,12))
ar3 = ar1.reshape((12,1))
print(ar1)
print(ar2)
print(ar3)

print(len(ar1))
print(len(ar2))

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4  5  6  7  8  9 10 11 12]]
[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]
12
1


- 拼接

In [86]:
ar1 = np.array(range(1,4))
ar2 = np.array(range(4,7))
ar3 = np.array(range(7,10))

ar_c1 = np.concatenate([ar1,ar2,ar3])
print(ar_c1)
ar_c2 = ar_c1.reshape((3,3))
ar_c3 = np.concatenate([ar_c2,ar1.reshape(1,3)])
print(ar_c3)
ar_c4 = np.concatenate([ar_c2,ar1.reshape(3,1),ar2.reshape(3,1)],axis = 1)
print(ar_c4)

ar_c5 = np.vstack([ar3,ar_c2,ar2])
print(ar_c5)
ar_c6 = np.hstack([ar3.reshape(3,1),ar_c2,ar2.reshape(3,1)])
print(ar_c6)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]]
[[1 2 3 1 4]
 [4 5 6 2 5]
 [7 8 9 3 6]]
[[7 8 9]
 [1 2 3]
 [4 5 6]
 [7 8 9]
 [4 5 6]]
[[7 1 2 3 4]
 [8 4 5 6 5]
 [9 7 8 9 6]]


- 分裂

In [237]:
print(ar_c1)
ar_s = np.split(ar_c1,[3,6])
print(ar_s)

[1 2 3 4 5 6 7 8 9]
[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


In [87]:
print(ar_c2)
ar_vs = np.vsplit(ar_c2,[1,2])
print(ar_vs)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]


In [88]:
print(ar_c2)
ar_hs = np.hsplit(ar_c2,[1,2])
print(ar_hs)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]


In [89]:
ar_c6

array([[7, 1, 2, 3, 4],
       [8, 4, 5, 6, 5],
       [9, 7, 8, 9, 6]])

In [90]:
ar_c6.T

array([[7, 8, 9],
       [1, 4, 7],
       [2, 5, 8],
       [3, 6, 9],
       [4, 5, 6]])

### 2.1.5 函数

- 循环“也”很慢

In [91]:
ar1 = np.arange(1000000)
l1 = list(range(1000000))

In [94]:
%time  ar1 = ar1 * 2

CPU times: user 2.56 ms, sys: 1.13 ms, total: 3.7 ms
Wall time: 1.98 ms


In [95]:
%time  l1 = [li*2 for li in l1]

CPU times: user 63.8 ms, sys: 15.7 ms, total: 79.6 ms
Wall time: 78.8 ms


- 高级函数： map
- 匿名函数 lambda

In [96]:
%time l1 =map(lambda x:x*2,l1)

CPU times: user 3 µs, sys: 0 ns, total: 3 µs
Wall time: 5.72 µs


In [97]:
l1[0]

TypeError: 'map' object is not subscriptable

In [98]:
l1 = list(range(1000000))

In [99]:
%time l1 = list(map(lambda x:x*2,l1))

CPU times: user 111 ms, sys: 15.8 ms, total: 127 ms
Wall time: 127 ms


In [265]:
def db2(x):
    return x*2

In [267]:
%time l1 = list(map(db2,l1))

CPU times: user 114 ms, sys: 19.5 ms, total: 133 ms
Wall time: 132 ms


In [269]:
%time l1 = np.array(map(db2,ar1))

CPU times: user 56.2 ms, sys: 6.05 ms, total: 62.2 ms
Wall time: 62 ms


In [ ]:
`

In [100]:

ar = np.array(range(1,13)).reshape((3,4))
ar

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [101]:
ar*2

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [103]:
ar+2.5

array([[ 3.5,  4.5,  5.5,  6.5],
       [ 7.5,  8.5,  9.5, 10.5],
       [11.5, 12.5, 13.5, 14.5]])

In [282]:
# +-*/ // ** %
print(-ar)
np.abs(-ar)


[[ -1  -2  -3  -4]
 [ -5  -6  -7  -8]
 [ -9 -10 -11 -12]]


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [283]:
np.sin(ar) #sin cos tan arcsin

array([[ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ],
       [-0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825],
       [ 0.41211849, -0.54402111, -0.99999021, -0.53657292]])

In [285]:
np.log(ar) #log,log2,log10,exp,exp2,power,

array([[0.        , 0.69314718, 1.09861229, 1.38629436],
       [1.60943791, 1.79175947, 1.94591015, 2.07944154],
       [2.19722458, 2.30258509, 2.39789527, 2.48490665]])

In [286]:
x = [0, 0.001, 0.01, 0.1]
print("exp(x) - 1 =", np.expm1(x))
print("log(1 + x) =", np.log1p(x))

exp(x) - 1 = [0.         0.0010005  0.01005017 0.10517092]
log(1 + x) = [0.         0.0009995  0.00995033 0.09531018]


In [104]:
ar_c2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [105]:
ar_c2 * ar_c2

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [296]:
ar_c2.dot(ar_c2)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

- reduce

In [301]:
from functools import reduce
l1 = list(range(101))
l2 = int(reduce(lambda x,y:x+y,l1))
print(l2)

5050


![a1.png](juhe.png)

In [303]:
ar

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [304]:
ar.sum()

78

In [313]:
np.argmax(ar)

11

In [316]:
np.percentile(ar,80)

9.8

In [311]:
np.quantile(ar,0.8)

9.8

- 排序

![knuth](knuth.jpg)

In [111]:
ar = np.random.randint(0,20,20)
ar

array([ 9, 10,  1,  1,  7,  9,  3,  6, 11, 14, 18,  0, 14,  3, 12, 10, 11,
        4,  6,  4])

In [123]:
ar=np.sort(ar)[::-1]

In [124]:
ar

array([18, 14, 14, 12, 11, 11, 10, 10,  9,  9,  7,  6,  6,  4,  4,  3,  3,
        1,  1,  0])

In [120]:
ar

array([ 0,  1,  1,  3,  3,  4,  4,  6,  6,  7,  9,  9, 10, 10, 11, 11, 12,
       14, 14, 18])

In [112]:
np.argsort(ar)

array([11,  2,  3, 13,  6, 19, 17,  7, 18,  4,  0,  5, 15,  1,  8, 16, 14,
       12,  9, 10])

In [113]:
ar.sort()
ar

array([ 0,  1,  1,  3,  3,  4,  4,  6,  6,  7,  9,  9, 10, 10, 11, 11, 12,
       14, 14, 18])

In [114]:
l1 = list(ar)
l1

[0, 1, 1, 3, 3, 4, 4, 6, 6, 7, 9, 9, 10, 10, 11, 11, 12, 14, 14, 18]

In [125]:
l1.sort?

In [115]:
l1.sort(key = lambda x:x%3)
l1

[0, 3, 3, 6, 6, 9, 9, 12, 18, 1, 1, 4, 4, 7, 10, 10, 11, 11, 14, 14]

In [116]:
mat = np.random.randint(0,20,20).reshape((4,5))
mat

array([[15,  3, 12,  4,  8],
       [14, 15,  3, 15, 13],
       [16, 17,  5,  9,  3],
       [ 0,  5,  0, 17, 18]])

In [117]:
np.sort(mat,axis = 0)

array([[ 0,  3,  0,  4,  3],
       [14,  5,  3,  9,  8],
       [15, 15,  5, 15, 13],
       [16, 17, 12, 17, 18]])

In [118]:
np.sort(mat,axis = 1)

array([[ 3,  4,  8, 12, 15],
       [ 3, 13, 14, 15, 15],
       [ 3,  5,  9, 16, 17],
       [ 0,  0,  5, 17, 18]])

## 2.2 Pandas

In [126]:
import pandas as pd

### 2.2.1 pandas基础

- Seires 加索引的ndarray

In [127]:
l1 = list(range(5))
l1

[0, 1, 2, 3, 4]

In [128]:
ar1 = np.array(l1)
ar1

array([0, 1, 2, 3, 4])

In [129]:
sr1 = pd.Series(ar1)
#pd.Series(data,index = index)
sr1

0    0
1    1
2    2
3    3
4    4
dtype: int64

In [130]:
sr1.values

array([0, 1, 2, 3, 4])

In [131]:
sr1[1:3]

1    1
2    2
dtype: int64

In [132]:
sr2 = pd.Series(np.arange(5)/4,index = ['a',2,'中文',0.25,'a'])
sr2

a       0.00
2       0.25
中文      0.50
0.25    0.75
a       1.00
dtype: float64

可以认为，series是科学计算世界中的字典扩展

In [133]:
sr2['a']

a    0.0
a    1.0
dtype: float64

In [134]:
dict3 = {'a':0,2:0.25,'中文':0.5,0.25:0.75,'a':1}
sr3 = pd.Series(dict3)
print(sr3['a'])
sr3

1.0


a       1.00
2       0.25
中文      0.50
0.25    0.75
dtype: float64

In [370]:
dict3

{'a': 1, 2: 0.25, '中文': 0.5, 0.25: 0.75}

- DataFrame

In [135]:
dict1 = {}
dict2 = {}
np.random.seed(0)
rdi = np.random.randint(10,100,(10))
print(rdi)
for li in rdi:
    dict1[li] = li//10
    dict2[li] = li%10
sr_10 = pd.Series(dict1)
sr_1 = pd.Series(dict2)
df1 = pd.DataFrame({'十位':sr_10,'digit':sr_1})
df1

[54 57 74 77 77 19 93 31 46 97]


十位  digit
54   5      4
57   5      7
74   7      4
77   7      7
19   1      9
93   9      3
31   3      1
46   4      6
97   9      7

dataframe便是一个二层的字典，每个value是一个series

In [394]:
df1['digit']

54    4
57    7
74    4
77    7
19    9
93    3
31    1
46    6
97    7
Name: digit, dtype: int64

In [395]:
df1['digit'][54]

4

In [136]:
df1.loc[54]

十位       5
digit    4
Name: 54, dtype: int64

In [403]:
df1.loc[54,'digit']

4

In [404]:
df1.loc[[54,57,77]]

十位  digit
54   5      4
57   5      7
77   7      7

In [406]:
df1.iloc[:3,:1]

十位
54   5
57   5
74   7

In [408]:
df1.loc[:77,:'digit']

十位  digit
54   5      4
57   5      7
74   7      4
77   7      7

In [137]:
df1.ix[:77,:1]

/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


十位
54   5
57   5
74   7
77   7

In [138]:
dict3 = {}
dict4 = {}
for di in rdi:
    if di%2 == 0:
        dict3[di] = di//10
    else:
        dict4[di] = di%10
df2 = pd.DataFrame({'十位':pd.Series(dict3),'digit':pd.Series(dict4)})
df2

十位  digit
19  NaN    9.0
31  NaN    1.0
46  4.0    NaN
54  5.0    NaN
57  NaN    7.0
74  7.0    NaN
77  NaN    7.0
93  NaN    3.0
97  NaN    7.0

- 处理缺失值

In [410]:
df2['digit'].sum()

34.0

In [139]:
df2.isnull()

十位  digit
19   True  False
31   True  False
46  False   True
54  False   True
57   True  False
74  False   True
77   True  False
93   True  False
97   True  False

In [140]:
df2.notnull()

十位  digit
19  False   True
31  False   True
46   True  False
54   True  False
57  False   True
74   True  False
77  False   True
93  False   True
97  False   True

In [141]:
df2.dropna()  #删除整行

Empty DataFrame
Columns: [十位, digit]
Index: []

In [143]:
df2.fillna(-1)

十位  digit
19 -1.0    9.0
31 -1.0    1.0
46  4.0   -1.0
54  5.0   -1.0
57 -1.0    7.0
74  7.0   -1.0
77 -1.0    7.0
93 -1.0    3.0
97 -1.0    7.0

In [144]:
df2.fillna(method = 'ffill')

十位  digit
19  NaN    9.0
31  NaN    1.0
46  4.0    1.0
54  5.0    1.0
57  5.0    7.0
74  7.0    7.0
77  7.0    7.0
93  7.0    3.0
97  7.0    7.0

In [145]:
df2.fillna(method = 'bfill')

十位  digit
19  4.0    9.0
31  4.0    1.0
46  4.0    7.0
54  5.0    7.0
57  7.0    7.0
74  7.0    7.0
77  NaN    7.0
93  NaN    3.0
97  NaN    7.0

In [418]:
df2.fillna(method = 'bfill',axis=1)

十位  digit
19  9.0    9.0
31  1.0    1.0
46  4.0    NaN
54  5.0    NaN
57  7.0    7.0
74  7.0    NaN
77  7.0    7.0
93  3.0    3.0
97  7.0    7.0

In [146]:
df2.fillna({'十位':100,'digit':-1})

十位  digit
19  100.0    9.0
31  100.0    1.0
46    4.0   -1.0
54    5.0   -1.0
57  100.0    7.0
74    7.0   -1.0
77  100.0    7.0
93  100.0    3.0
97  100.0    7.0

In [147]:
df2

十位  digit
19  NaN    9.0
31  NaN    1.0
46  4.0    NaN
54  5.0    NaN
57  NaN    7.0
74  7.0    NaN
77  NaN    7.0
93  NaN    3.0
97  NaN    7.0

In [148]:
df2.fillna({'十位':100,'digit':-1},limit=2)

十位  digit
19  100.0    9.0
31  100.0    1.0
46    4.0   -1.0
54    5.0   -1.0
57    NaN    7.0
74    7.0    NaN
77    NaN    7.0
93    NaN    3.0
97    NaN    7.0

In [149]:
df2.fillna(0,inplace = True)
df2

十位  digit
19  0.0    9.0
31  0.0    1.0
46  4.0    0.0
54  5.0    0.0
57  0.0    7.0
74  7.0    0.0
77  0.0    7.0
93  0.0    3.0
97  0.0    7.0

- 合并数据集

- pd.concate 用于纵向合并
- pd.merge 用于横向合并

In [150]:
df1

十位  digit
54   5      4
57   5      7
74   7      4
77   7      7
19   1      9
93   9      3
31   3      1
46   4      6
97   9      7

In [151]:
dict3 = {}
dict4 = {}
dict5 = {}
np.random.seed(0)
rdi2 = np.random.randint(100,900,(10))
for di in rdi2:
    dict3[di] = di//100
    dict4[di] = di%100//10
    dict5[di] = di%10
df3 = pd.DataFrame({'百位':pd.Series(dict3),'十位':pd.Series(dict4),'digit':pd.Series(dict5)})
df3

百位  十位  digit
784   7   8      4
659   6   5      9
729   7   2      9
292   2   9      2
863   8   6      3
807   8   0      7
459   4   5      9
109   1   0      9
823   8   2      3
377   3   7      7

In [152]:
df_c1 = pd.concat([df1,df3])
df_c1

/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


digit  十位   百位
54       4   5  NaN
57       7   5  NaN
74       4   7  NaN
77       7   7  NaN
19       9   1  NaN
93       3   9  NaN
31       1   3  NaN
46       6   4  NaN
97       7   9  NaN
784      4   8  7.0
659      9   5  6.0
729      9   2  7.0
292      2   9  2.0
863      3   6  8.0
807      7   0  8.0
459      9   5  4.0
109      9   0  1.0
823      3   2  8.0
377      7   7  3.0

In [443]:
pd.concat([df1,df3],join='inner')

十位  digit
54    5      4
57    5      7
74    7      4
77    7      7
19    1      9
93    9      3
31    3      1
46    4      6
97    9      7
784   8      4
659   5      9
729   2      9
292   9      2
863   6      3
807   0      7
459   5      9
109   0      9
823   2      3
377   7      7

In [153]:
pd.concat([df1,df3],join='outer')

/usr/local/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: Sorting because non-concatenation axis is not aligned. A future version
of pandas will change to not sort by default.

To accept the future behavior, pass 'sort=False'.

To retain the current behavior and silence the warning, pass 'sort=True'.

  """Entry point for launching an IPython kernel.


digit  十位   百位
54       4   5  NaN
57       7   5  NaN
74       4   7  NaN
77       7   7  NaN
19       9   1  NaN
93       3   9  NaN
31       1   3  NaN
46       6   4  NaN
97       7   9  NaN
784      4   8  7.0
659      9   5  6.0
729      9   2  7.0
292      2   9  2.0
863      3   6  8.0
807      7   0  8.0
459      9   5  4.0
109      9   0  1.0
823      3   2  8.0
377      7   7  3.0

- merge

In [154]:
df4 = pd.DataFrame({'十位':pd.Series(dict4),'digit':pd.Series(dict5)})
df5 = pd.DataFrame({'十位':pd.Series(dict4),'百位':pd.Series(dict3)})

In [155]:
pd.merge(df4,df5)

十位  digit  百位
0    8      4   7
1    5      9   6
2    5      9   4
3    5      9   6
4    5      9   4
5    2      9   7
6    2      9   8
7    2      3   7
8    2      3   8
9    9      2   2
10   6      3   8
11   0      7   8
12   0      7   1
13   0      9   8
14   0      9   1
15   7      7   3

In [158]:
pd.merge(df1,df3,on='digit')
pd.merge?

In [159]:
pd.merge(df1,df3,on='digit',how='outer')

十位_x  digit   百位  十位_y
0    5.0      4  7.0   8.0
1    7.0      4  7.0   8.0
2    5.0      7  8.0   0.0
3    5.0      7  3.0   7.0
4    7.0      7  8.0   0.0
5    7.0      7  3.0   7.0
6    9.0      7  8.0   0.0
7    9.0      7  3.0   7.0
8    1.0      9  6.0   5.0
9    1.0      9  7.0   2.0
10   1.0      9  4.0   5.0
11   1.0      9  1.0   0.0
12   9.0      3  8.0   6.0
13   9.0      3  8.0   2.0
14   3.0      1  NaN   NaN
15   4.0      6  NaN   NaN
16   NaN      2  2.0   9.0

- groupby

In [160]:
df6 = pd.merge(df4,df5)
df6

十位  digit  百位
0    8      4   7
1    5      9   6
2    5      9   4
3    5      9   6
4    5      9   4
5    2      9   7
6    2      9   8
7    2      3   7
8    2      3   8
9    9      2   2
10   6      3   8
11   0      7   8
12   0      7   1
13   0      9   8
14   0      9   1
15   7      7   3

In [161]:
df6.groupby('digit').sum()  #bysort

十位  百位
digit        
2       9   2
3      10  23
4       8   7
7       7  12
9      24  44

- 和list互动

In [162]:
all_res = []
for ii in range(10):
    this_line = {}
    this_line['num'] = ii
    this_line['奇偶'] = 0   #0是奇数
    if ii % 2 == 0:
        this_line['奇偶'] = 1
    all_res.append(this_line)

In [163]:
import json
js = json.dumps(all_res, sort_keys=True, indent=4, separators=(',', ':'),ensure_ascii=False)
print(js)

[
    {
        "num":0,
        "奇偶":1
    },
    {
        "num":1,
        "奇偶":0
    },
    {
        "num":2,
        "奇偶":1
    },
    {
        "num":3,
        "奇偶":0
    },
    {
        "num":4,
        "奇偶":1
    },
    {
        "num":5,
        "奇偶":0
    },
    {
        "num":6,
        "奇偶":1
    },
    {
        "num":7,
        "奇偶":0
    },
    {
        "num":8,
        "奇偶":1
    },
    {
        "num":9,
        "奇偶":0
    }
]


In [164]:
df_l = pd.DataFrame(all_res)
df_l

num  奇偶
0    0   1
1    1   0
2    2   1
3    3   0
4    4   1
5    5   0
6    6   1
7    7   0
8    8   1
9    9   0

In [165]:
root_dir = '/Users/wjy/python/course/'

In [473]:
df_l.to_csv(root_dir+'df_l.csv',encoding='utf-8_sig')

In [475]:
df_in = pd.read_csv(root_dir+'df_l.csv')

In [166]:
df6.describe()

十位      digit         百位
count  16.000000  16.000000  16.000000
mean    3.625000   6.750000   5.500000
std     3.008322   2.744692   2.607681
min     0.000000   2.000000   1.000000
25%     1.500000   3.750000   3.750000
50%     3.500000   8.000000   6.500000
75%     5.250000   9.000000   8.000000
max     9.000000   9.000000   8.000000